### ISSUE TITLE
kawpow-stratum-pool module integration

### ISSUE THREAD

**Issue by edradev** [MintPond/hasher-kawpow#1]
How to use with the kawpow-stratum-pool module?

**Comment by JCThePants** [comment]
You would have to work out how to program it in. I'm not familiar with the kawpow-stratum-pool but shouldn't it already have built-in kawpow verification?

**Comment by edradev** [comment]
I'm not programmer and I dont how to. I need help how to built in that validator. My raven daemon shows that kind of errors:
ERROR: ProcessNewBlock: AcceptBlock FAILED (proof of work failed)
ERROR: CheckBlock: Consensus::CheckBlockHeader: high-hash, proof of work failed (code 16)

Someone said that kawpowd validator do the trick but not mention how.
